version: '3'

services:
  db:
    image: redis:5.0.4-alpine3.9
    container_name: Redis
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - mysql-data:/var/lib/mysql
      # - ./data/db:/var/lib/mysql
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
